name: Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:lts

    services:
      ganache:
        image: trufflesuite/ganache-cli
        ports:
          - 8545:8545

    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn build
    - run: yarn test
      env:
        JSON_RPC_URL: http://ganache:8545
